# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Selenium WebDriver CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Restore/Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run test1
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject1 tests"	  
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
    - name: Run test2
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject2 tests"	  
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
    - name: Run test3
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject3 tests"	  
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
